### ISSUE TITLE
Blank screen?

### ISSUE THREAD

**Issue by jordanwilliams1** [sk89q/WarmRoast#8]
So when I Run WarmRoast I Just get this:

https://i.gyazo.com/dcb10efb3472b6b7f09fb3e131900aa0.png

.. A Blank screen, Any idea why? I'm using this command:

java -Djava.library.path=/usr/lib/jvm/java-8-oracle/jre/bin -cp /usr/lib/jvm/java-8-oracle/lib/tools.jar:warmroast-1.0.0-SNAPSHOT.jar com.sk89q.warmroast.WarmRoast --thread "Server thread"

After I Run this I get this:

https://i.gyazo.com/5fe34b3098311a699deeecba91102fca.png

I Pick number 3, So I type "3" then when I go the webpage its just blank like that :(

**Comment by sk89q** [comment]
You need to click "View sampler results"
